server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.jzgemhyeegnuhnaeffpj
    password: MindMend
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 94EZ1mGyOUmBV8QpfmJK4h2gS/1zqbjS4PzrOeHrnHo=
  expiration-ms: 86400000

app:
  supabase:
    url:     ${SUPABASE_URL:https://jzgemhyeegnuhnaeffpj.supabase.co}
    anon-key: ${SUPABASE_ANON_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9…}

ia:
  base-url: ${IA_BASE_URL}

